# Generated by Django 3.1.3 on 2020-12-07 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inasistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('I', 'Inasistencia a clase'), ('T', 'Llegada tardía')], max_length=1)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.estudiante')),
                ('profesor', models.ForeignKey(help_text='Profesor que ha registrado la falta.', on_delete=django.db.models.deletion.CASCADE, to='personas.profesor')),
            ],
        ),
    ]
